package org.upyog.rs.repository.querybuilder;

public class DriverDetailsQueryBuilder {

    public static final String DRIVER_QUERY = new StringBuilder()
            .append("SELECT ")
            .append("ursbd.booking_id, ")
            .append("ursbd.booking_no, ")
            .append("ursbd.tenant_id, ")
            .append("ursbd.tanker_type, ")
            .append("ursbd.tanker_quantity, ")
            .append("ursbd.water_quantity, ")
            .append("ursbd.address_detail_id, ")
            .append("ursbd.mobile_number, ")
            .append("ursbd.locality_code, ")
            .append("ursbd.payment_receipt_filestore_id, ")
            .append("ursbd.water_type, ")
            .append("ursbd.description, ")
            .append("ursbd.applicant_uuid, ")
            .append("ursbd.delivery_date, ")
            .append("ursbd.delivery_time, ")
            .append("ursbd.extra_charge, ")
            .append("ursbd.vendor_id, ")
            .append("ursbd.vehicle_id, ")
            .append("ursbd.driver_id, ")
            .append("ursbd.vehicle_type, ")
            .append("ursbd.vehicle_capacity, ")
            .append("ursbd.booking_createdby, ")
            .append("ursbd.booking_status, ")
            .append("ursbd.createdby, ")
            .append("ursbd.lastmodifiedby, ")
            .append("ursbd.createdtime, ")
            .append("ursbd.lastmodifiedtime, ")
            .append("urad.name AS applicant_name, ")
            .append("urad.mobile_number AS applicant_mobile, ")
            .append("urad.email_id AS applicant_email, ")
            .append("uraddr.house_no, ")
            .append("uraddr.address_line_1, ")
            .append("uraddr.address_line_2, ")
            .append("uraddr.street_name, ")
            .append("uraddr.landmark, ")
            .append("uraddr.city, ")
            .append("uraddr.pincode, ")
            .append("uraddr.latitude, ")
            .append("uraddr.longitude, ")

            .append("edt.id AS trip_id, ")
            .append("edt.booking_id AS trip_booking_id, ")
            .append("edt.booking_no AS trip_booking_no, ")
            .append("edt.tanker_type AS trip_tanker_type, ")
            .append("edt.vendor_id AS trip_vendor_id, ")
            .append("edt.vehicle_id AS trip_vehicle_id, ")
            .append("edt.driver_id AS trip_driver_id, ")
            .append("edt.current_status AS trip_current_status, ")
            .append("edt.start_latitude AS trip_start_latitude, ")
            .append("edt.start_longitude AS trip_start_longitude, ")
            .append("edt.start_file_store_id AS trip_start_file_store_id, ")
            .append("edt.end_latitude AS trip_end_latitude, ")
            .append("edt.end_longitude AS trip_end_longitude, ")
            .append("edt.end_file_store_id AS trip_end_file_store_id, ")
            .append("edt.remark AS trip_remark, ")
            .append("edt.created_by AS trip_created_by, ")
            .append("edt.created_time AS trip_created_time, ")
            .append("edt.last_modified_by AS trip_last_modified_by, ")
            .append("edt.last_modified_time AS trip_last_modified_time, ")
            .append("uraddr.locality_code AS address_locality_code, ")
            .append("ev.registrationnumber AS registrationNumber, ")
            .append("ev.model AS vehicle_model ")
            .append("FROM upyog_rs_water_tanker_booking_details ursbd ")
            .append("INNER JOIN upyog_rs_water_tanker_applicant_details urad ON ursbd.booking_id = urad.booking_id ")
            .append("INNER JOIN upyog_rs_water_tanker_address_details uraddr ON urad.applicant_id = uraddr.applicant_id ")
            .append("LEFT JOIN eg_vehicle ev ON ursbd.vehicle_id = ev.id ")
            .append("LEFT JOIN eg_driver_trip edt ON ursbd.booking_id = edt.booking_id ")
            .append("WHERE ursbd.driver_id = ?")
            .toString();
}